# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Use any version between 15.2.31.300 and 15.2.31.570
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  #config.vm.box_version = "15.2.31.354"
  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network "forwarded_port", guest: 22, host: 2000 # Master Node SSH
  config.vm.network "forwarded_port", guest: 6443, host: 6443 # Kubectl API Access
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # API Access
  config.vm.network "forwarded_port", guest: 16686, host: 16686 # Jaeger HTTP Access
  config.vm.network "forwarded_port", guest: 16687, host: 16687 # Jaeger CR Access
  config.vm.network "forwarded_port", guest: 32368 , host: 32368
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #   # Customize the amount of memory on the VM:clear
    vb.memory = "4096"
    vb.name = "k3s"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     sudo zypper refresh
     sudo zypper --non-interactive install bzip2
     sudo zypper --non-interactive install etcd
     sudo zypper --non-interactive install lsof
     sudo zypper --non-interactive install htop
     sudo zypper --non-interactive install net-tools
     sudo zypper --non-interactive install wget
     sudo zypper --non-interactive install apparmor-parser
     sudo zypper --non-interactive install k9s
     sudo zypper --non-interactive install bind-utils
  SHELL

  args = []
      config.vm.provision "k3s shell script", type: "shell",
          path: "k3s.sh",
          args: args
end
