apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-sample-app
  labels:
    name: second-sample-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-sample-app
  template:
    metadata:
      labels:
        app: second-sample-app
    spec:
      containers:
        - name: second-sample-app
          image: ghcr.io/thejaysmith/my-sample-app:v2
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8000
              protocol: TCP